### ISSUE TITLE
TODO: migration of OBS Service cargo audit

### ISSUE THREAD

**Issue by uncomfyhalomacro** [openSUSE/obs-service-cargo_vendor#38]
# Current plans
- [x] Manual source parameters:
  - [x] SrcTar
  - [x] SrcDir
- [ ] Automatic Source Detection by reading `_service` file that contains `cargo_vendor` if manual way is both empty.
  - [x] Read XML and use `cargo_vendor` parameters instead.
- [ ] Check existence of `Cargo.lock`
- [ ] Warn if `cargo_vendor`'s `update` parameter is `false`.

## Miscellaneous Tasks

- [x] Support tags in vendor
- [x] Refactor vendor #40 
- [ ] Use cargo vendor filterer #37
